version: '3.8'

services:
  php:
    build: .
    container_name: symfony_php
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    networks:
      - symfony_net

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge
